import { db } from '@/db';
import { session } from '@/db/schema';

async function main() {
    const sampleSessions = [
        // Completed sessions (50 total)
        {
            experimentId: 1,
            participantId: 1,
            status: 'completed',
            startedAt: new Date('2024-01-15T09:00:00Z').toISOString(),
            completedAt: new Date('2024-01-15T09:35:00Z').toISOString(),
            demographics: JSON.stringify({ age: 25, gender: 'female', education_level: 'bachelors', handedness: 'right' }),
        },
        {
            experimentId: 1,
            participantId: 2,
            status: 'completed',
            startedAt: new Date('2024-01-15T10:30:00Z').toISOString(),
            completedAt: new Date('2024-01-15T11:15:00Z').toISOString(),
            demographics: JSON.stringify({ age: 32, gender: 'male', education_level: 'masters', handedness: 'right' }),
        },
        {
            experimentId: 2,
            participantId: 3,
            status: 'completed',
            startedAt: new Date('2024-01-16T14:00:00Z').toISOString(),
            completedAt: new Date('2024-01-16T14:45:00Z').toISOString(),
            demographics: JSON.stringify({ age: 28, gender: 'non-binary', education_level: 'bachelors', handedness: 'left' }),
        },
        {
            experimentId: 2,
            participantId: 4,
            status: 'completed',
            startedAt: new Date('2024-01-16T15:30:00Z').toISOString(),
            completedAt: new Date('2024-01-16T16:10:00Z').toISOString(),
            demographics: JSON.stringify({ age: 45, gender: 'female', education_level: 'doctorate', handedness: 'right' }),
        },
        {
            experimentId: 3,
            participantId: 5,
            status: 'completed',
            startedAt: new Date('2024-01-17T09:15:00Z').toISOString(),
            completedAt: new Date('2024-01-17T09:50:00Z').toISOString(),
            demographics: JSON.stringify({ age: 22, gender: 'male', education_level: 'high_school', handedness: 'right' }),
        },
        {
            experimentId: 3,
            participantId: 6,
            status: 'completed',
            startedAt: new Date('2024-01-17T11:00:00Z').toISOString(),
            completedAt: new Date('2024-01-17T11:55:00Z').toISOString(),
            demographics: JSON.stringify({ age: 38, gender: 'female', education_level: 'masters', handedness: 'ambidextrous' }),
        },
        {
            experimentId: 4,
            participantId: 7,
            status: 'completed',
            startedAt: new Date('2024-01-18T13:00:00Z').toISOString(),
            completedAt: new Date('2024-01-18T13:40:00Z').toISOString(),
            demographics: JSON.stringify({ age: 29, gender: 'male', education_level: 'bachelors', handedness: 'right' }),
        },
        {
            experimentId: 4,
            participantId: 8,
            status: 'completed',
            startedAt: new Date('2024-01-18T14:30:00Z').toISOString(),
            completedAt: new Date('2024-01-18T15:20:00Z').toISOString(),
            demographics: JSON.stringify({ age: 41, gender: 'female', education_level: 'doctorate', handedness: 'left' }),
        },
        {
            experimentId: 5,
            participantId: 9,
            status: 'completed',
            startedAt: new Date('2024-01-19T10:00:00Z').toISOString(),
            completedAt: new Date('2024-01-19T10:45:00Z').toISOString(),
            demographics: JSON.stringify({ age: 26, gender: 'male', education_level: 'bachelors', handedness: 'right' }),
        },
        {
            experimentId: 5,
            participantId: 10,
            status: 'completed',
            startedAt: new Date('2024-01-19T12:00:00Z').toISOString(),
            completedAt: new Date('2024-01-19T12:50:00Z').toISOString(),
            demographics: JSON.stringify({ age: 34, gender: 'female', education_level: 'masters', handedness: 'right' }),
        },
        {
            experimentId: 6,
            participantId: 11,
            status: 'completed',
            startedAt: new Date('2024-01-22T09:00:00Z').toISOString(),
            completedAt: new Date('2024-01-22T09:30:00Z').toISOString(),
            demographics: JSON.stringify({ age: 27, gender: 'non-binary', education_level: 'bachelors', handedness: 'left' }),
        },
        {
            experimentId: 6,
            participantId: 12,
            status: 'completed',
            startedAt: new Date('2024-01-22T11:00:00Z').toISOString(),
            completedAt: new Date('2024-01-22T11:55:00Z').toISOString(),
            demographics: JSON.stringify({ age: 51, gender: 'male', education_level: 'doctorate', handedness: 'right' }),
        },
        {
            experimentId: 7,
            participantId: 13,
            status: 'completed',
            startedAt: new Date('2024-01-23T13:30:00Z').toISOString(),
            completedAt: new Date('2024-01-23T14:15:00Z').toISOString(),
            demographics: JSON.stringify({ age: 23, gender: 'female', education_level: 'bachelors', handedness: 'right' }),
        },
        {
            experimentId: 7,
            participantId: 14,
            status: 'completed',
            startedAt: new Date('2024-01-23T15:00:00Z').toISOString(),
            completedAt: new Date('2024-01-23T15:40:00Z').toISOString(),
            demographics: JSON.stringify({ age: 36, gender: 'male', education_level: 'masters', handedness: 'right' }),
        },
        {
            experimentId: 8,
            participantId: 15,
            status: 'completed',
            startedAt: new Date('2024-01-24T10:15:00Z').toISOString(),
            completedAt: new Date('2024-01-24T11:00:00Z').toISOString(),
            demographics: JSON.stringify({ age: 30, gender: 'female', education_level: 'bachelors', handedness: 'left' }),
        },
        {
            experimentId: 8,
            participantId: 16,
            status: 'completed',
            startedAt: new Date('2024-01-24T13:00:00Z').toISOString(),
            completedAt: new Date('2024-01-24T13:50:00Z').toISOString(),
            demographics: JSON.stringify({ age: 44, gender: 'male', education_level: 'doctorate', handedness: 'right' }),
        },
        {
            experimentId: 9,
            participantId: 17,
            status: 'completed',
            startedAt: new Date('2024-01-25T09:30:00Z').toISOString(),
            completedAt: new Date('2024-01-25T10:25:00Z').toISOString(),
            demographics: JSON.stringify({ age: 28, gender: 'female', education_level: 'masters', handedness: 'right' }),
        },
        {
            experimentId: 9,
            participantId: 18,
            status: 'completed',
            startedAt: new Date('2024-01-25T11:30:00Z').toISOString(),
            completedAt: new Date('2024-01-25T12:20:00Z').toISOString(),
            demographics: JSON.stringify({ age: 33, gender: 'male', education_level: 'bachelors', handedness: 'ambidextrous' }),
        },
        {
            experimentId: 10,
            participantId: 19,
            status: 'completed',
            startedAt: new Date('2024-01-26T14:00:00Z').toISOString(),
            completedAt: new Date('2024-01-26T14:35:00Z').toISOString(),
            demographics: JSON.stringify({ age: 25, gender: 'non-binary', education_level: 'bachelors', handedness: 'left' }),
        },
        {
            experimentId: 10,
            participantId: 20,
            status: 'completed',
            startedAt: new Date('2024-01-26T15:30:00Z').toISOString(),
            completedAt: new Date('2024-01-26T16:10:00Z').toISOString(),
            demographics: JSON.stringify({ age: 39, gender: 'female', education_level: 'masters', handedness: 'right' }),
        },
        {
            experimentId: 1,
            participantId: 21,
            status: 'completed',
            startedAt: new Date('2024-01-29T09:00:00Z').toISOString(),
            completedAt: new Date('2024-01-29T09:45:00Z').toISOString(),
            demographics: JSON.stringify({ age: 31, gender: 'male', education_level: 'doctorate', handedness: 'right' }),
        },
        {
            experimentId: 2,
            participantId: 22,
            status: 'completed',
            startedAt: new Date('2024-01-29T11:00:00Z').toISOString(),
            completedAt: new Date('2024-01-29T11:50:00Z').toISOString(),
            demographics: JSON.stringify({ age: 27, gender: 'female', education_level: 'bachelors', handedness: 'right' }),
        },
        {
            experimentId: 3,
            participantId: 23,
            status: 'completed',
            startedAt: new Date('2024-01-30T13:15:00Z').toISOString(),
            completedAt: new Date('2024-01-30T14:00:00Z').toISOString(),
            demographics: JSON.stringify({ age: 42, gender: 'male', education_level: 'masters', handedness: 'left' }),
        },
        {
            experimentId: 4,
            participantId: 24,
            status: 'completed',
            startedAt: new Date('2024-01-30T15:00:00Z').toISOString(),
            completedAt: new Date('2024-01-30T15:55:00Z').toISOString(),
            demographics: JSON.stringify({ age: 24, gender: 'female', education_level: 'bachelors', handedness: 'right' }),
        },
        {
            experimentId: 5,
            participantId: 25,
            status: 'completed',
            startedAt: new Date('2024-01-31T10:00:00Z').toISOString(),
            completedAt: new Date('2024-01-31T10:40:00Z').toISOString(),
            demographics: JSON.stringify({ age: 35, gender: 'male', education_level: 'masters', handedness: 'right' }),
        },
        {
            experimentId: 6,
            participantId: 26,
            status: 'completed',
            startedAt: new Date('2024-01-31T12:30:00Z').toISOString(),
            completedAt: new Date('2024-01-31T13:15:00Z').toISOString(),
            demographics: JSON.stringify({ age: 29, gender: 'female', education_level: 'bachelors', handedness: 'left' }),
        },
        {
            experimentId: 7,
            participantId: 27,
            status: 'completed',
            startedAt: new Date('2024-02-01T09:30:00Z').toISOString(),
            completedAt: new Date('2024-02-01T10:20:00Z').toISOString(),
            demographics: JSON.stringify({ age: 48, gender: 'male', education_level: 'doctorate', handedness: 'right' }),
        },
        {
            experimentId: 8,
            participantId: 28,
            status: 'completed',
            startedAt: new Date('2024-02-01T11:00:00Z').toISOString(),
            completedAt: new Date('2024-02-01T11:45:00Z').toISOString(),
            demographics: JSON.stringify({ age: 26, gender: 'non-binary', education_level: 'bachelors', handedness: 'ambidextrous' }),
        },
        {
            experimentId: 9,
            participantId: 29,
            status: 'completed',
            startedAt: new Date('2024-02-02T14:00:00Z').toISOString(),
            completedAt: new Date('2024-02-02T14:50:00Z').toISOString(),
            demographics: JSON.stringify({ age: 37, gender: 'female', education_level: 'masters', handedness: 'right' }),
        },
        {
            experimentId: 10,
            participantId: 30,
            status: 'completed',
            startedAt: new Date('2024-02-02T16:00:00Z').toISOString(),
            completedAt: new Date('2024-02-02T16:35:00Z').toISOString(),
            demographics: JSON.stringify({ age: 22, gender: 'male', education_level: 'bachelors', handedness: 'right' }),
        },
        {
            experimentId: 1,
            participantId: 31,
            status: 'completed',
            startedAt: new Date('2024-02-05T09:00:00Z').toISOString(),
            completedAt: new Date('2024-02-05T09:55:00Z').toISOString(),
            demographics: JSON.stringify({ age: 40, gender: 'female', education_level: 'doctorate', handedness: 'left' }),
        },
        {
            experimentId: 2,
            participantId: 32,
            status: 'completed',
            startedAt: new Date('2024-02-05T11:30:00Z').toISOString(),
            completedAt: new Date('2024-02-05T12:10:00Z').toISOString(),
            demographics: JSON.stringify({ age: 28, gender: 'male', education_level: 'masters', handedness: 'right' }),
        },
        {
            experimentId: 3,
            participantId: 33,
            status: 'completed',
            startedAt: new Date('2024-02-06T13:00:00Z').toISOString(),
            completedAt: new Date('2024-02-06T13:50:00Z').toISOString(),
            demographics: JSON.stringify({ age: 32, gender: 'female', education_level: 'bachelors', handedness: 'right' }),
        },
        {
            experimentId: 4,
            participantId: 34,
            status: 'completed',
            startedAt: new Date('2024-02-06T15:00:00Z').toISOString(),
            completedAt: new Date('2024-02-06T15:40:00Z').toISOString(),
            demographics: JSON.stringify({ age: 46, gender: 'male', education_level: 'masters', handedness: 'right' }),
        },
        {
            experimentId: 5,
            participantId: 35,
            status: 'completed',
            startedAt: new Date('2024-02-07T10:15:00Z').toISOString(),
            completedAt: new Date('2024-02-07T11:00:00Z').toISOString(),
            demographics: JSON.stringify({ age: 24, gender: 'non-binary', education_level: 'bachelors', handedness: 'left' }),
        },
        {
            experimentId: 6,
            participantId: 36,
            status: 'completed',
            startedAt: new Date('2024-02-07T13:00:00Z').toISOString(),
            completedAt: new Date('2024-02-07T13:45:00Z').toISOString(),
            demographics: JSON.stringify({ age: 38, gender: 'female', education_level: 'doctorate', handedness: 'right' }),
        },
        {
            experimentId: 7,
            participantId: 37,
            status: 'completed',
            startedAt: new Date('2024-02-08T09:30:00Z').toISOString(),
            completedAt: new Date('2024-02-08T10:25:00Z').toISOString(),
            demographics: JSON.stringify({ age: 27, gender: 'male', education_level: 'bachelors', handedness: 'ambidextrous' }),
        },
        {
            experimentId: 8,
            participantId: 38,
            status: 'completed',
            startedAt: new Date('2024-02-08T11:30:00Z').toISOString(),
            completedAt: new Date('2024-02-08T12:20:00Z').toISOString(),
            demographics: JSON.stringify({ age: 43, gender: 'female', education_level: 'masters', handedness: 'right' }),
        },
        {
            experimentId: 9,
            participantId: 39,
            status: 'completed',
            startedAt: new Date('2024-02-09T14:00:00Z').toISOString(),
            completedAt: new Date('2024-02-09T14:35:00Z').toISOString(),
            demographics: JSON.stringify({ age: 25, gender: 'male', education_level: 'bachelors', handedness: 'right' }),
        },
        {
            experimentId: 10,
            participantId: 40,
            status: 'completed',
            startedAt: new Date('2024-02-09T15:30:00Z').toISOString(),
            completedAt: new Date('2024-02-09T16:15:00Z').toISOString(),
            demographics: JSON.stringify({ age: 36, gender: 'female', education_level: 'masters', handedness: 'left' }),
        },
        {
            experimentId: 1,
            participantId: 1,
            status: 'completed',
            startedAt: new Date('2024-02-12T09:00:00Z').toISOString(),
            completedAt: new Date('2024-02-12T09:50:00Z').toISOString(),
            demographics: JSON.stringify({ age: 25, gender: 'female', education_level: 'bachelors', handedness: 'right' }),
        },
        {
            experimentId: 2,
            participantId: 5,
            status: 'completed',
            startedAt: new Date('2024-02-12T11:00:00Z').toISOString(),
            completedAt: new Date('2024-02-12T11:40:00Z').toISOString(),
            demographics: JSON.stringify({ age: 22, gender: 'male', education_level: 'high_school', handedness: 'right' }),
        },
        {
            experimentId: 3,
            participantId: 10,
            status: 'completed',
            startedAt: new Date('2024-02-13T13:15:00Z').toISOString(),
            completedAt: new Date('2024-02-13T14:05:00Z').toISOString(),
            demographics: JSON.stringify({ age: 34, gender: 'female', education_level: 'masters', handedness: 'right' }),
        },
        {
            experimentId: 4,
            participantId: 15,
            status: 'completed',
            startedAt: new Date('2024-02-13T15:00:00Z').toISOString(),
            completedAt: new Date('2024-02-13T15:45:00Z').toISOString(),
            demographics: JSON.stringify({ age: 30, gender: 'female', education_level: 'bachelors', handedness: 'left' }),
        },
        {
            experimentId: 5,
            participantId: 20,
            status: 'completed',
            startedAt: new Date('2024-02-14T10:00:00Z').toISOString(),
            completedAt: new Date('2024-02-14T10:55:00Z').toISOString(),
            demographics: JSON.stringify({ age: 39, gender: 'female', education_level: 'masters', handedness: 'right' }),
        },
        {
            experimentId: 6,
            participantId: 25,
            status: 'completed',
            startedAt: new Date('2024-02-14T12:30:00Z').toISOString(),
            completedAt: new Date('2024-02-14T13:10:00Z').toISOString(),
            demographics: JSON.stringify({ age: 35, gender: 'male', education_level: 'masters', handedness: 'right' }),
        },
        {
            experimentId: 7,
            participantId: 30,
            status: 'completed',
            startedAt: new Date('2024-02-15T09:30:00Z').toISOString(),
            completedAt: new Date('2024-02-15T10:15:00Z').toISOString(),
            demographics: JSON.stringify({ age: 22, gender: 'male', education_level: 'bachelors', handedness: 'right' }),
        },
        {
            experimentId: 8,
            participantId: 35,
            status: 'completed',
            startedAt: new Date('2024-02-15T11:00:00Z').toISOString(),
            completedAt: new Date('2024-02-15T11:50:00Z').toISOString(),
            demographics: JSON.stringify({ age: 24, gender: 'non-binary', education_level: 'bachelors', handedness: 'left' }),
        },
        {
            experimentId: 9,
            participantId: 40,
            status: 'completed',
            startedAt: new Date('2024-02-16T14:00:00Z').toISOString(),
            completedAt: new Date('2024-02-16T14:40:00Z').toISOString(),
            demographics: JSON.stringify({ age: 36, gender: 'female', education_level: 'masters', handedness: 'left' }),
        },
        {
            experimentId: 10,
            participantId: 45,
            status: 'completed',
            startedAt: new Date('2024-02-16T16:00:00Z').toISOString(),
            completedAt: new Date('2024-02-16T16:45:00Z').toISOString(),
            demographics: JSON.stringify({ age: 29, gender: 'male', education_level: 'bachelors', handedness: 'right' }),
        },
        {
            experimentId: 1,
            participantId: 41,
            status: 'completed',
            startedAt: new Date('2024-02-19T09:00:00Z').toISOString(),
            completedAt: new Date('2024-02-19T09:35:00Z').toISOString(),
            demographics: JSON.stringify({ age: 33, gender: 'female', education_level: 'masters', handedness: 'right' }),
        },
        {
            experimentId: 2,
            participantId: 42,
            status: 'completed',
            startedAt: new Date('2024-02-19T11:30:00Z').toISOString(),
            completedAt: new Date('2024-02-19T12:20:00Z').toISOString(),
            demographics: JSON.stringify({ age: 47, gender: 'male', education_level: 'doctorate', handedness: 'right' }),
        },
        {
            experimentId: 3,
            participantId: 43,
            status: 'completed',
            startedAt: new Date('2024-02-20T13:00:00Z').toISOString(),
            completedAt: new Date('2024-02-20T13:50:00Z').toISOString(),
            demographics: JSON.stringify({ age: 26, gender: 'female', education_level: 'bachelors', handedness: 'left' }),
        },
        {
            experimentId: 4,
            participantId: 44,
            status: 'completed',
            startedAt: new Date('2024-02-20T15:00:00Z').toISOString(),
            completedAt: new Date('2024-02-20T15:40:00Z').toISOString(),
            demographics: JSON.stringify({ age: 31, gender: 'male', education_level: 'masters', handedness: 'right' }),
        },

        // In progress sessions (15 total)
        {
            experimentId: 5,
            participantId: 46,
            status: 'in_progress',
            startedAt: new Date('2024-02-21T10:00:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 6,
            participantId: 47,
            status: 'in_progress',
            startedAt: new Date('2024-02-21T11:30:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 7,
            participantId: 48,
            status: 'in_progress',
            startedAt: new Date('2024-02-21T13:15:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 8,
            participantId: 49,
            status: 'in_progress',
            startedAt: new Date('2024-02-21T14:45:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 9,
            participantId: 50,
            status: 'in_progress',
            startedAt: new Date('2024-02-22T09:00:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 10,
            participantId: 51,
            status: 'in_progress',
            startedAt: new Date('2024-02-22T10:30:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 1,
            participantId: 52,
            status: 'in_progress',
            startedAt: new Date('2024-02-22T12:00:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 2,
            participantId: 53,
            status: 'in_progress',
            startedAt: new Date('2024-02-22T13:30:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 3,
            participantId: 54,
            status: 'in_progress',
            startedAt: new Date('2024-02-22T15:00:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 4,
            participantId: 55,
            status: 'in_progress',
            startedAt: new Date('2024-02-23T09:15:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 5,
            participantId: 3,
            status: 'in_progress',
            startedAt: new Date('2024-02-23T10:45:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 6,
            participantId: 8,
            status: 'in_progress',
            startedAt: new Date('2024-02-23T12:00:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 7,
            participantId: 13,
            status: 'in_progress',
            startedAt: new Date('2024-02-23T13:30:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 8,
            participantId: 18,
            status: 'in_progress',
            startedAt: new Date('2024-02-23T15:00:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 9,
            participantId: 23,
            status: 'in_progress',
            startedAt: new Date('2024-02-24T09:00:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },

        // Abandoned sessions (10 total)
        {
            experimentId: 10,
            participantId: 28,
            status: 'abandoned',
            startedAt: new Date('2024-02-24T10:30:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 1,
            participantId: 33,
            status: 'abandoned',
            startedAt: new Date('2024-02-24T11:45:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 2,
            participantId: 38,
            status: 'abandoned',
            startedAt: new Date('2024-02-24T13:00:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 3,
            participantId: 2,
            status: 'abandoned',
            startedAt: new Date('2024-02-24T14:30:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 4,
            participantId: 7,
            status: 'abandoned',
            startedAt: new Date('2024-02-25T09:00:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 5,
            participantId: 12,
            status: 'abandoned',
            startedAt: new Date('2024-02-25T10:15:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 6,
            participantId: 17,
            status: 'abandoned',
            startedAt: new Date('2024-02-25T11:30:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 7,
            participantId: 22,
            status: 'abandoned',
            startedAt: new Date('2024-02-25T13:00:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 8,
            participantId: 27,
            status: 'abandoned',
            startedAt: new Date('2024-02-25T14:15:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 9,
            participantId: 32,
            status: 'abandoned',
            startedAt: new Date('2024-02-25T15:30:00Z').toISOString(),
            completedAt: null,
            demographics: null,
        },

        // Pending sessions (5 total)
        {
            experimentId: 10,
            participantId: 37,
            status: 'pending',
            startedAt: null,
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 1,
            participantId: 4,
            status: 'pending',
            startedAt: null,
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 2,
            participantId: 9,
            status: 'pending',
            startedAt: null,
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 3,
            participantId: 14,
            status: 'pending',
            startedAt: null,
            completedAt: null,
            demographics: null,
        },
        {
            experimentId: 4,
            participantId: 19,
            status: 'pending',
            startedAt: null,
            completedAt: null,
            demographics: null,
        },
    ];

    await db.insert(session).values(sampleSessions);
    
    console.log('✅ Sessions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});